### ISSUE TITLE
[Feature] Add support for variable to disable scorecards support

### ISSUE THREAD

**Issue by raphaelvarieras** [fivetran/dbt_greenhouse#16]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Add support for var:
    greenhouse_using_scorecards: false

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @raphaelvarieras thanks for opening this issue! I believe adding a variable to disable the scorecard source should be simple enough.

Before accepting this Issue I did want to clarify the reason for the scorecard removal. My understanding of the interview process within Greenhouse is that Interviews are accompanied by a scorecard to properly evaluate the interview. Are there situations where a scorecard is not utilized?

**Comment by raphaelvarieras** [comment]
I am honestly not sure - I just don't see anything related to scorecards in our database schema and an error is preventing us from using the package as a result.

**Comment by raphaelvarieras** [comment]
Yes, we do use scorecards. They are in fact disabled in Fivetran UI but they are greyed out so I don't have the ability to enable them (yet I am connected with Site Admin credentials).

<img width="506" alt="image" src="https://user-images.githubusercontent.com/6558178/208503554-bee92bd2-efbe-4658-92f0-e126800402d3.png">

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for confirming this @raphaelvarieras. This seems to be the core of the issue. I would prefer we get the table synced into your warehouse and you are able to leverage accurate data as opposed to building the workaround within the package.

Unfortunately, I do not have visibility into the inner workings of the connector behavior and why your credentials may not be working. I would recommend opening a [Support Ticket](https://support.fivetran.com/hc/en-us) so our customer support team will be able to help you sync your scorecard table.

**Comment by raphaelvarieras** [comment]
Okey dokey - ticket open with support.

**Comment by fivetran-joemarkiewicz** [comment]
Sounds great, thanks @raphaelvarieras and please let me know if you continue to encounter any issues once you are able to sync this table.

For the time being, this is not a feature we will integrate into the package. As such, I will close this ticket. Please feel free to open a new issue if you encounter any other errors once you are able to sync the scorecard table.
